# Generated by Django 6.0.7 on 2026-07-12 17:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('e_centro', models.BooleanField(default=False, help_text="Marque como True para o 'Centro' — ajuda a filtrar rotas de/para o centro.", verbose_name='É o centro da cidade?')),
            ],
            options={
                'verbose_name': 'Localidade',
                'verbose_name_plural': 'Localidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='transportes.empresa')),
                ('destino', models.ForeignKey(blank=True, help_text='Deixe em branco para linhas urbanadas circulares (sem destinofix).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linhas_destino', to='transportes.localidade')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas_origem', to='transportes.localidade')),
            ],
            options={
                'verbose_name': 'Linha',
                'verbose_name_plural': 'Linhas',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_saida', models.TimeField()),
                ('via', models.CharField(blank=True, help_text="Trajeto/pontos por onde passa, ex: 'Tanac / São Paulo'.", max_length=225)),
                ('frequencia', models.CharField(choices=[('SEG_SEX', 'Segunda a Sexta'), ('SEG_SAB', 'Segunda a Sábado'), ('TODOS_DIAS', 'Todos os dias'), ('DOM_FERIADOS', 'Domingos e Feriados')], max_length=20)),
                ('preco_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='transportes.linha')),
            ],
            options={
                'verbose_name': 'Horário',
                'verbose_name_plural': 'Horários',
                'ordering': ['hora_saida'],
            },
        ),
        migrations.AddConstraint(
            model_name='linha',
            constraint=models.UniqueConstraint(fields=('nome', 'empresa'), name='linha_nome_unico_por_empresa'),
        ),
    ]
