# Generated by Django 6.0.7 on 2026-07-12 03:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('e_centro', models.BooleanField(default=False, help_text="Marque como True para o 'Centro' — ajuda a filtrar rotas de/para o centro.", verbose_name='É o centro da cidade?')),
            ],
            options={
                'verbose_name': 'Localidade',
                'verbose_name_plural': 'Localidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas_destino', to='transportes.localidade')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='transportes.empresa')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas_origem', to='transportes.localidade')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_saida', models.TimeField()),
                ('preco_estimado', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='transportes.rota')),
            ],
            options={
                'verbose_name': 'Horário',
                'verbose_name_plural': 'Horários',
                'ordering': ['dia_semana', 'hora_saida'],
            },
        ),
        migrations.AddConstraint(
            model_name='rota',
            constraint=models.UniqueConstraint(fields=('origem', 'destino', 'empresa'), name='rota_unica_por_empresa'),
        ),
    ]
