# Generated by Django 6.0.7 on 2026-07-12 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linha',
            name='tipo',
            field=models.CharField(choices=[('INTERMUNICIPAL', 'Intermunicipal'), ('INTERIORANO', 'Interiorano'), ('URBANO', 'Urbano'), ('SELETIVO', 'Seletivo')], default='URBANO', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linha',
            name='destino',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para linhas urbanas circulares (sem destino fixo).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linhas_destino', to='transportes.localidade'),
        ),
    ]
