# Generated by Django 6.0.7 on 2026-07-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Informações extras: pontos de embarque/desembarque, condições especiais etc.'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='frequencia',
            field=models.CharField(choices=[('SEG_SEX', 'Segunda a Sexta'), ('SEG_SAB', 'Segunda a Sábado'), ('TODOS_DIAS', 'Todos os dias'), ('SABADO', 'Sábado'), ('DOM_FERIADOS', 'Domingos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='horario',
            name='via',
            field=models.CharField(blank=True, help_text="Trajeto/pontos por onde passa, ex: 'Tanac / São Paulo'.", max_length=225),
        ),
    ]
