# Generated by Django 6.0.7 on 2026-07-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0002_horario_observacoes_alter_horario_frequencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='frequencia',
            field=models.CharField(choices=[('SEG_SEX', 'Segunda a Sexta'), ('SEG_SAB', 'Segunda a Sábado'), ('TODOS_DIAS', 'Todos os dias'), ('QUARTA', 'Quarta-feira'), ('SABADO', 'Sábados'), ('DOM_FERIADOS', 'Domingos')], max_length=20),
        ),
    ]
