# Generated by Django 6.0.7 on 2026-07-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0003_alter_horario_frequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='trajeto',
            field=models.CharField(blank=True, help_text="Descrição do circuito completo, ex: 'Rodoviária / Germano Henke / Centro / Santo Antônio / Rodoviária'.", max_length=255),
        ),
    ]
