# Generated by Django 6.0.7 on 2026-07-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0004_horario_trajeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='trajeto',
        ),
    ]
