# Generated by Django 6.0.7 on 2026-07-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0005_remove_horario_trajeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='frequencia',
            field=models.CharField(choices=[('SEG_SEX', '2ª a 6ª'), ('SEG_SAB', '2ª a Sábado'), ('TODOS_DIAS', 'Diário'), ('QUARTA', 'Quarta-feira'), ('SABADO', 'Sábado'), ('DOM_FERIADOS', 'Domingo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='horario',
            name='sentido',
            field=models.CharField(help_text='Ex.: Rodoviária, Germano Henke, Hospital Montenegro...', max_length=120),
        ),
    ]
